<tbody><tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=accesosdered" title="Click to view the schema definition for attribute type: accesosdered">accesosdered</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[accesosdered][0]" id="new_values_accesosdered_0" value="3"><div id="ajADDVALUEaccesosdered"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=accesosdered" title="Add an additional value to attribute accesosdered" onclick="return ajDISPLAY('ADDVALUEaccesosdered','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=accesosdered&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=accesostemporales" title="Click to view the schema definition for attribute type: accesostemporales">accesostemporales</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[accesostemporales][0]" id="new_values_accesostemporales_0" value="NO"><div id="ajADDVALUEaccesostemporales"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=accesostemporales" title="Add an additional value to attribute accesostemporales" onclick="return ajDISPLAY('ADDVALUEaccesostemporales','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=accesostemporales&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=accesovh" title="Click to view the schema definition for attribute type: accesovh">accesovh</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[accesovh][0]" id="new_values_accesovh_0" value="NO"><div id="ajADDVALUEaccesovh"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=accesovh" title="Add an additional value to attribute accesovh" onclick="return ajDISPLAY('ADDVALUEaccesovh','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=accesovh&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=aliascuentagoogle" title="Click to view the schema definition for attribute type: aliascuentagoogle">aliascuentagoogle</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="mailto:aaguilar@transportespitic.com.mx"><img src="images/default/mail.png" alt="Mail" style="float: right;"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[aliascuentagoogle][0]" id="new_values_aliascuentagoogle_0" value="aaguilar@transportespitic.com.mx"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="mailto:aaguilar@transportespitic.com"><img src="images/default/mail.png" alt="Mail" style="float: right;"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[aliascuentagoogle][1]" id="new_values_aliascuentagoogle_1" value="aaguilar@transportespitic.com"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="mailto:aaguilar@transportespitic.mx"><img src="images/default/mail.png" alt="Mail" style="float: right;"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[aliascuentagoogle][2]" id="new_values_aliascuentagoogle_2" value="aaguilar@transportespitic.mx"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="mailto:aaguilar@tpitic.com"><img src="images/default/mail.png" alt="Mail" style="float: right;"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[aliascuentagoogle][3]" id="new_values_aliascuentagoogle_3" value="aaguilar@tpitic.com"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="mailto:aaguilar@tpitic.mx"><img src="images/default/mail.png" alt="Mail" style="float: right;"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[aliascuentagoogle][4]" id="new_values_aliascuentagoogle_4" value="aaguilar@tpitic.mx"><div id="ajADDVALUEaliascuentagoogle"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=aliascuentagoogle" title="Add an additional value to attribute aliascuentagoogle" onclick="return ajDISPLAY('ADDVALUEaliascuentagoogle','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=aliascuentagoogle&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=aliasdecorreo" title="Click to view the schema definition for attribute type: aliasdecorreo">aliasdecorreo</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[aliasdecorreo][0]" id="new_values_aliasdecorreo_0" value="userspiticcorp_jc"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[aliasdecorreo][1]" id="new_values_aliasdecorreo_1" value="mexicali"><div id="ajADDVALUEaliasdecorreo"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=aliasdecorreo" title="Add an additional value to attribute aliasdecorreo" onclick="return ajDISPLAY('ADDVALUEaliasdecorreo','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=aliasdecorreo&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=aliasgoogle" title="Click to view the schema definition for attribute type: aliasgoogle">aliasgoogle</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[aliasgoogle][0]" id="new_values_aliasgoogle_0" value="user1"><div id="ajADDVALUEaliasgoogle"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=aliasgoogle" title="Add an additional value to attribute aliasgoogle" onclick="return ajDISPLAY('ADDVALUEaliasgoogle','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=aliasgoogle&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=anfitrion" title="Click to view the schema definition for attribute type: anfitrion">anfitrion</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a title="DN not available 0"><img src="images/default/nogo.png" alt="Go"></a>&nbsp;</td><td valign="top"><span style="white-space: nowrap;"><input type="text" class="value" name="new_values[anfitrion][0]" id="new_values_anfitrion_0" value="0">&nbsp;<a href="javascript:dnChooserPopup('entry_form','new_values_anfitrion_0','');" title="Click to popup a dialog to select an entry (DN) graphically"><img class="chooser" src="images/default/find.png" alt="Find"></a></span>
<div id="ajADDVALUEanfitrion"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=anfitrion" title="Add an additional value to attribute anfitrion" onclick="return ajDISPLAY('ADDVALUEanfitrion','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=anfitrion&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=chofer" title="Click to view the schema definition for attribute type: chofer">chofer</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[chofer][0]" id="new_values_chofer_0" value="0"><div id="ajADDVALUEchofer"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=chofer" title="Add an additional value to attribute chofer" onclick="return ajDISPLAY('ADDVALUEchofer','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=chofer&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=clavetelefono" title="Click to view the schema definition for attribute type: claveTelefono">claveTelefono</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[clavetelefono][0]" id="new_values_clavetelefono_0" value="NO"><div id="ajADDVALUEclavetelefono"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=claveTelefono" title="Add an additional value to attribute claveTelefono" onclick="return ajDISPLAY('ADDVALUEclavetelefono','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=claveTelefono&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=cn" title="Click to view the schema definition for attribute type: cn">cn</a></td><td class="note"><sup><small><acronym title="Required attribute for objectClass(es) posixAccount inetOrgPerson organizationalPerson person ">required</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[cn][0]" id="new_values_cn_0" value="Arturo Aguilar Ochoa"><div id="ajADDVALUEcn"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=cn" title="Add an additional value to attribute cn" onclick="return ajDISPLAY('ADDVALUEcn','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=cn&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=cobrador" title="Click to view the schema definition for attribute type: cobrador">cobrador</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[cobrador][0]" id="new_values_cobrador_0" value="0"><div id="ajADDVALUEcobrador"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=cobrador" title="Add an additional value to attribute cobrador" onclick="return ajDISPLAY('ADDVALUEcobrador','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=cobrador&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=correo" title="Click to view the schema definition for attribute type: correo">correo</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[correo][0]" id="new_values_correo_0" value="1"><div id="ajADDVALUEcorreo"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=correo" title="Add an additional value to attribute correo" onclick="return ajDISPLAY('ADDVALUEcorreo','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=correo&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=deptorh" title="Click to view the schema definition for attribute type: deptorh">deptorh</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[deptorh][0]" id="new_values_deptorh_0" value="5"><div id="ajADDVALUEdeptorh"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=deptorh" title="Add an additional value to attribute deptorh" onclick="return ajDISPLAY('ADDVALUEdeptorh','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=deptorh&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=mail" title="Click to view the schema definition for attribute type: mail">Email</a></td><td class="note"><sup><small><acronym title="Note: 'Email' is an alias for 'mail'">alias</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="mailto:aaguilar@tpitic.com.mx"><img src="images/default/mail.png" alt="Mail" style="float: right;"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[mail][0]" id="new_values_mail_0" value="aaguilar@tpitic.com.mx"><div id="ajADDVALUEmail"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=mail" title="Add an additional value to attribute mail" onclick="return ajDISPLAY('ADDVALUEmail','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=mail&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=employeetype" title="Click to view the schema definition for attribute type: employeeType">employeeType</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[employeetype][0]" id="new_values_employeetype_0" value="user"><div id="ajADDVALUEemployeetype"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=employeeType" title="Add an additional value to attribute employeeType" onclick="return ajDISPLAY('ADDVALUEemployeetype','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=employeeType&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=extension" title="Click to view the schema definition for attribute type: extension">extension</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[extension][0]" id="new_values_extension_0" value="NO"><div id="ajADDVALUEextension"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=extension" title="Add an additional value to attribute extension" onclick="return ajDISPLAY('ADDVALUEextension','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=extension&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=feriacustom1" title="Click to view the schema definition for attribute type: feriacustom1">feriacustom1</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[feriacustom1][0]" id="new_values_feriacustom1_0" value="4"><div id="ajADDVALUEferiacustom1"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=feriacustom1" title="Add an additional value to attribute feriacustom1" onclick="return ajDISPLAY('ADDVALUEferiacustom1','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=feriacustom1&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=gidnumber" title="Click to view the schema definition for attribute type: gidNumber">gidNumber</a></td><td class="note"><sup><small><acronym title="Required attribute for objectClass(es) posixAccount ">required</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[gidnumber][0]" id="new_values_gidnumber_0" value="100"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
</td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=givenname" title="Click to view the schema definition for attribute type: givenName">givenName</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[givenname][0]" id="new_values_givenname_0" value="Arturo"><div id="ajADDVALUEgivenname"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=givenName" title="Add an additional value to attribute givenName" onclick="return ajDISPLAY('ADDVALUEgivenname','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=givenName&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=homedirectory" title="Click to view the schema definition for attribute type: homeDirectory">homeDirectory</a></td><td class="note"><sup><small><acronym title="Required attribute for objectClass(es) posixAccount ">required</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[homedirectory][0]" id="new_values_homedirectory_0" value="/home/directorynotset"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
</td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=jabber" title="Click to view the schema definition for attribute type: jabber">jabber</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[jabber][0]" id="new_values_jabber_0" value="0"><div id="ajADDVALUEjabber"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=jabber" title="Add an additional value to attribute jabber" onclick="return ajDISPLAY('ADDVALUEjabber','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=jabber&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=lanip" title="Click to view the schema definition for attribute type: lanip">lanip</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[lanip][0]" id="new_values_lanip_0" value="192.168.13.110"><div id="ajADDVALUElanip"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=lanip" title="Add an additional value to attribute lanip" onclick="return ajDISPLAY('ADDVALUElanip','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=lanip&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=lanmac" title="Click to view the schema definition for attribute type: lanmac">lanmac</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[lanmac][0]" id="new_values_lanmac_0" value="C0:3F:D5:B9:D9:AE"><div id="ajADDVALUElanmac"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=lanmac" title="Add an additional value to attribute lanmac" onclick="return ajDISPLAY('ADDVALUElanmac','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=lanmac&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=licenciagoogle" title="Click to view the schema definition for attribute type: licenciagoogle">licenciagoogle</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[licenciagoogle][0]" id="new_values_licenciagoogle_0" value="Lite"><div id="ajADDVALUElicenciagoogle"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=licenciagoogle" title="Add an additional value to attribute licenciagoogle" onclick="return ajDISPLAY('ADDVALUElicenciagoogle','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=licenciagoogle&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=livemeeting" title="Click to view the schema definition for attribute type: livemeeting">livemeeting</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[livemeeting][0]" id="new_values_livemeeting_0" value="NO"><div id="ajADDVALUElivemeeting"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=livemeeting" title="Add an additional value to attribute livemeeting" onclick="return ajDISPLAY('ADDVALUElivemeeting','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=livemeeting&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=loginshell" title="Click to view the schema definition for attribute type: loginShell">loginShell</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[loginshell][0]" id="new_values_loginshell_0" value="/bin/false"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
</td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=nivelrh" title="Click to view the schema definition for attribute type: nivelrh">nivelrh</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[nivelrh][0]" id="new_values_nivelrh_0" value="0"><div id="ajADDVALUEnivelrh"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=nivelrh" title="Add an additional value to attribute nivelrh" onclick="return ajDISPLAY('ADDVALUEnivelrh','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=nivelrh&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=nivelscup" title="Click to view the schema definition for attribute type: nivelscup">nivelscup</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[nivelscup][0]" id="new_values_nivelscup_0" value="0"><div id="ajADDVALUEnivelscup"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=nivelscup" title="Add an additional value to attribute nivelscup" onclick="return ajDISPLAY('ADDVALUEnivelscup','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=nivelscup&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=noempleado" title="Click to view the schema definition for attribute type: noempleado">noempleado</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[noempleado][0]" id="new_values_noempleado_0" value="9603"><div id="ajADDVALUEnoempleado"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=noempleado" title="Add an additional value to attribute noempleado" onclick="return ajDISPLAY('ADDVALUEnoempleado','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=noempleado&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=objectclass" title="Click to view the schema definition for attribute type: objectClass">objectClass</a></td><td class="note"><sup><small><acronym title="Required attribute for objectClass(es) top ">required</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=objectclasses&amp;viewvalue=top" title="View the schema description for this objectClass"><img src="images/default/info.png" alt="Info"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[objectclass][0]" id="new_values_objectclass_0" value="top"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=objectclasses&amp;viewvalue=posixAccount" title="View the schema description for this objectClass"><img src="images/default/info.png" alt="Info"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[objectclass][1]" id="new_values_objectclass_1" value="posixAccount"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=objectclasses&amp;viewvalue=inetOrgPerson" title="View the schema description for this objectClass"><img src="images/default/info.png" alt="Info"></a>&nbsp;</td><td valign="top"><input type="text" class="roval" name="new_values[objectclass][2]" id="new_values_objectclass_2" value="inetOrgPerson" readonly="readonly"> <small>(<acronym title="This is a structural ObjectClass and cannot be removed.">structural</acronym>)</small></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=objectclasses&amp;viewvalue=organizationalPerson" title="View the schema description for this objectClass"><img src="images/default/info.png" alt="Info"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[objectclass][3]" id="new_values_objectclass_3" value="organizationalPerson"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=objectclasses&amp;viewvalue=person" title="View the schema description for this objectClass"><img src="images/default/info.png" alt="Info"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[objectclass][4]" id="new_values_objectclass_4" value="person"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=objectclasses&amp;viewvalue=userinfo" title="View the schema description for this objectClass"><img src="images/default/info.png" alt="Info"></a>&nbsp;</td><td valign="top"><input type="text" class="value" name="new_values[objectclass][5]" id="new_values_objectclass_5" value="userinfo"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=objectClass" title="Add an additional value to attribute objectClass" onclick="return ajDISPLAY('BODY','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=objectClass','Add Value to Attribute');">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=office" title="Click to view the schema definition for attribute type: Office">Office</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[office][0]" id="new_values_office_0" value="0"><div id="ajADDVALUEoffice"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=Office" title="Add an additional value to attribute Office" onclick="return ajDISPLAY('ADDVALUEoffice','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=Office&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=oficina" title="Click to view the schema definition for attribute type: oficina">oficina</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[oficina][0]" id="new_values_oficina_0" value="MXL"><div id="ajADDVALUEoficina"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=oficina" title="Add an additional value to attribute oficina" onclick="return ajDISPLAY('ADDVALUEoficina','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=oficina&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=userpassword" title="Click to view the schema definition for attribute type: userPassword">Password</a></td><td class="note"><sup><small><acronym title="Note: 'Password' is an alias for 'userPassword'">alias</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><table cellspacing="0" cellpadding="0"><tbody><tr><td valign="top"><input type="password" class="value" name="new_values[userpassword][0]" id="new_values_userpassword_0" value="{SHA}cG9dIuPotmwhuqLUz6AS9dCSGiw="></td><td valign="top"><input type="hidden" name="post_value[userpassword][]" value="0"><select name="enc[userpassword][0]" id="enc_userpassword_0"><option value="">clear</option><option value="blowfish">blowfish</option><option value="crypt">crypt</option><option value="ext_des">ext_des</option><option value="md5">md5</option><option value="k5key">k5key</option><option value="md5crypt">md5crypt</option><option value="sha" selected="selected">sha</option><option value="smd5">smd5</option><option value="ssha">ssha</option></select></td></tr><tr><td valign="top"><small><a href="javascript:passwordComparePopup('new_values_userpassword_0','userpassword')">Check password...</a></small><br></td></tr></tbody></table><div id="ajADDVALUEuserpassword"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=userPassword" title="Add an additional value to attribute userPassword" onclick="return ajDISPLAY('ADDVALUEuserpassword','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=userPassword&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=puesto" title="Click to view the schema definition for attribute type: puesto">puesto</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[puesto][0]" id="new_values_puesto_0" value="aux operaciones"><div id="ajADDVALUEpuesto"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=puesto" title="Add an additional value to attribute puesto" onclick="return ajDISPLAY('ADDVALUEpuesto','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=puesto&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=roomnumber" title="Click to view the schema definition for attribute type: roomNumber">roomNumber</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[roomnumber][0]" id="new_values_roomnumber_0" value="MXL"><div id="ajADDVALUEroomnumber"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=roomNumber" title="Add an additional value to attribute roomNumber" onclick="return ajDISPLAY('ADDVALUEroomnumber','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=roomNumber&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=servicios" title="Click to view the schema definition for attribute type: servicios">servicios</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[servicios][0]" id="new_values_servicios_0" value="NO"><div id="ajADDVALUEservicios"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=servicios" title="Add an additional value to attribute servicios" onclick="return ajDISPLAY('ADDVALUEservicios','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=servicios&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=sn" title="Click to view the schema definition for attribute type: sn">sn</a></td><td class="note"><sup><small><acronym title="Required attribute for objectClass(es) inetOrgPerson organizationalPerson person ">required</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[sn][0]" id="new_values_sn_0" value="Aguilar Ochoa"><div id="ajADDVALUEsn"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=sn" title="Add an additional value to attribute sn" onclick="return ajDISPLAY('ADDVALUEsn','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=sn&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=uidnumber" title="Click to view the schema definition for attribute type: uidNumber">uidNumber</a></td><td class="note"><sup><small><acronym title="Required attribute for objectClass(es) posixAccount ">required</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[uidnumber][0]" id="new_values_uidnumber_0" value="25001575"></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
</td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=urlvip" title="Click to view the schema definition for attribute type: urlvip">urlvip</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"><a title="DN not available 0"><img src="images/default/nogo.png" alt="Go"></a>&nbsp;</td><td valign="top"><span style="white-space: nowrap;"><input type="text" class="value" name="new_values[urlvip][0]" id="new_values_urlvip_0" value="0">&nbsp;<a href="javascript:dnChooserPopup('entry_form','new_values_urlvip_0','');" title="Click to popup a dialog to select an entry (DN) graphically"><img class="chooser" src="images/default/find.png" alt="Find"></a></span>
<div id="ajADDVALUEurlvip"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=urlvip" title="Add an additional value to attribute urlvip" onclick="return ajDISPLAY('ADDVALUEurlvip','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=urlvip&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=uid" title="Click to view the schema definition for attribute type: uid">User Name</a></td><td class="note"><sup><small><acronym title="Note: 'User Name' is an alias for 'uid'">alias</acronym>, <acronym title="Required attribute for objectClass(es) posixAccount ">required</acronym>, <acronym title="This attribute is required for the RDN.">rdn</acronym></small></sup></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="roval" name="new_values[uid][0]" id="new_values_uid_0" value="aaguilar" readonly="readonly" style="background-color: white; color: black;"><div id="ajADDVALUEuid"></div></td><td valign="top" style="text-align: right;">*</td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=uid" title="Add an additional value to attribute uid" onclick="return ajDISPLAY('ADDVALUEuid','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=uid&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div><div class="add_value"><small>(<a href="cmd.php?cmd=rename_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;template=none">rename</a>)</small></div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=usomoviles" title="Click to view the schema definition for attribute type: UsoMoviles">UsoMoviles</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[usomoviles][0]" id="new_values_usomoviles_0" value="NO"><div id="ajADDVALUEusomoviles"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=UsoMoviles" title="Add an additional value to attribute UsoMoviles" onclick="return ajDISPLAY('ADDVALUEusomoviles','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=UsoMoviles&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=voiceip" title="Click to view the schema definition for attribute type: voiceip">voiceip</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[voiceip][0]" id="new_values_voiceip_0" value="NO"><div id="ajADDVALUEvoiceip"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=voiceip" title="Add an additional value to attribute voiceip" onclick="return ajDISPLAY('ADDVALUEvoiceip','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=voiceip&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=voicemac" title="Click to view the schema definition for attribute type: voicemac">voicemac</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[voicemac][0]" id="new_values_voicemac_0" value="NO"><div id="ajADDVALUEvoicemac"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=voicemac" title="Add an additional value to attribute voicemac" onclick="return ajDISPLAY('ADDVALUEvoicemac','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=voicemac&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=voicemodel" title="Click to view the schema definition for attribute type: voicemodel">voicemodel</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[voicemodel][0]" id="new_values_voicemodel_0" value="NO"><div id="ajADDVALUEvoicemodel"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=voicemodel" title="Add an additional value to attribute voicemodel" onclick="return ajDISPLAY('ADDVALUEvoicemodel','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=voicemodel&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=web" title="Click to view the schema definition for attribute type: web">web</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[web][0]" id="new_values_web_0" value="1"><div id="ajADDVALUEweb"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=web" title="Add an additional value to attribute web" onclick="return ajDISPLAY('ADDVALUEweb','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=web&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=wifiip" title="Click to view the schema definition for attribute type: wifiip">wifiip</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[wifiip][0]" id="new_values_wifiip_0" value="NO"><div id="ajADDVALUEwifiip"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=wifiip" title="Add an additional value to attribute wifiip" onclick="return ajDISPLAY('ADDVALUEwifiip','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=wifiip&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td class="title"><a href="cmd.php?cmd=schema&amp;server_id=1&amp;view=attributes&amp;viewvalue=wifimac" title="Click to view the schema definition for attribute type: wifimac">wifimac</a></td><td class="note"></td></tr><tr><td class="value" colspan="2"><table cellspacing="0" cellpadding="0" width="100%" border="0"><tbody><tr><td class="icon" style="width: 25px;"></td><td valign="top"><input type="text" class="value" name="new_values[wifimac][0]" id="new_values_wifimac_0" value="NO"><div id="ajADDVALUEwifimac"></div></td><td valign="top" style="text-align: right;"></td></tr></tbody></table>
<table class="entry" border="0"><tbody><tr><td style="width: 25px;">&nbsp;</td><td><div class="add_value">(<a href="cmd.php?cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=wifimac" title="Add an additional value to attribute wifimac" onclick="return ajDISPLAY('ADDVALUEwifimac','cmd=add_value_form&amp;server_id=1&amp;dn=uid%3Daaguilar%2Cou%3DPeople%2Cdc%3Dtransportespitic%2Cdc%3Dcom&amp;attr=wifimac&amp;raw=1','Add Value to Attribute',1);">add value</a>)</div></td></tr></tbody></table></td></tr>

<tr><td colspan="2" style="text-align: center;"><input type="submit" id="create_button" name="submit" value="Update Object"></td></tr></tbody>